[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "20.9.0"

[[forms]]
  name = "contact"
  email = { subject = "New Contact Form Submission", recipient = "hellenkiwagama@gmail.com" }
